"""empty message

Revision ID: 02759b5e82e4
Revises: 5f1daf4e4357
Create Date: 2023-07-01 02:50:24.075583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02759b5e82e4'
down_revision = '5f1daf4e4357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stablishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stablishments_name', sa.String(length=120), nullable=False),
    sa.Column('stablishments_links', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stablishments_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stablishments')
    # ### end Alembic commands ###
