"""empty message

Revision ID: 4e380a0094cf
Revises: 
Create Date: 2023-07-18 21:31:10.376863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e380a0094cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stablishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stablishments_name', sa.String(length=120), nullable=False),
    sa.Column('stablishments_links', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stablishments_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_provider', sa.String(length=120), nullable=False),
    sa.Column('last_four', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('card_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stablishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card', sa.Integer(), nullable=False),
    sa.Column('stablishment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['stablishment'], ['stablishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stablishments')
    op.drop_table('cards')
    op.drop_table('user')
    op.drop_table('stablishments')
    # ### end Alembic commands ###
