"""empty message

Revision ID: 518910b0b98e
Revises: 8c15181cf704
Create Date: 2023-06-27 02:24:04.167664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518910b0b98e'
down_revision = '8c15181cf704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stablishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stablishments_name', sa.String(length=120), nullable=False),
    sa.Column('stablishments_links', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stablishments_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stablishments')
    # ### end Alembic commands ###
