"""empty message

Revision ID: 9eae93db0da0
Revises: e59ee516d766
Create Date: 2023-07-06 16:16:39.161232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eae93db0da0'
down_revision = 'e59ee516d766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
